server:
  port: 8080
  servlet:
    context-path: /

spring:
  jackson:
    deserialization:
      fail_on_unknown_properties: false
  application:
    name: anabilim-purchase-be

  datasource:
    url: jdbc:postgresql://localhost:5433/purchase
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: your-super-secret-jwt-key-here-make-it-long-and-secure-for-production
  expiration: 86400000  # 24 saat
  refresh-expiration: 604800000  # 7 gün

logging:
  level:
    root: INFO
    com.anabilim.purchase: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

