version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=purchase
      - POSTGRES_USER=anabilim
      - POSTGRES_PASSWORD=anabilimpass
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - anabilim-network
  anabilim-purchase-fe:
    image: ysfaltn/anabilim-purchase-fe:latest
    container_name: anabilim-purchase-fe
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      anabilim-network:
        aliases:
          - postgres-db

  anabilim-purchase-be:
    image: ysfaltn/anabilim-purchase-be:latest
    container_name: anabilim-purchase-be
    restart: unless-stopped
    depends_on:
      - postgres-db
    ports:
      - 8091:8080
    environment:
      - DB_HOST=10.0.1.2
      - DB_PORT=5432
      - DB_USERNAME=anabilim
      - DB_PASSWORD=anabilimpass
      - MAIL_USERNAME=your-email@example.com
      - MAIL_PASSWORD=your-mail-password
      - JWT_SECRET=your-super-secret-jwt-key-that-is-very-long-and-secure
    networks:
      - anabilim-network

volumes:
  postgres_data:

networks:
  anabilim-network:
    driver: bridge
