ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS order_number VARCHAR(100);
ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS byod BOOLEAN DEFAULT FALSE;
ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS warranty_months INT;
ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS lifespan_end_date TIMESTAMP;
ALTER TABLE stock_items ADD COLUMN IF NOT EXISTS school_id BIGINT;
